import type {Database} from "../database.js";

type ClientChangeRow={id:string;project_id:string;project_name:string;unit_id:string;unit_code:string;party_id:string;party_name:string;sales_case_id:string|null;title:string;description:string|null;source_type:string;catalog_item_code:string|null;category:string;status:string;surcharge_amount:string|null;currency:string;requested_at:string;due_at:string|null;created_at:string;updated_at:string};

function dto(row:ClientChangeRow){return{id:row.id,projectId:row.project_id,projectName:row.project_name,unitId:row.unit_id,unitCode:row.unit_code,partyId:row.party_id,partyName:row.party_name,salesCaseId:row.sales_case_id,title:row.title,description:row.description,sourceType:row.source_type,catalogItemCode:row.catalog_item_code,category:row.category,status:row.status,surchargeAmount:row.surcharge_amount===null?null:Number(row.surcharge_amount),currency:row.currency,requestedAt:row.requested_at,dueAt:row.due_at,createdAt:row.created_at,updatedAt:row.updated_at};}

const select=`SELECT change.id,change.project_id,project.name project_name,change.unit_id,unit.code unit_code,change.party_id,party.display_name party_name,change.sales_case_id,change.title,change.description,change.source_type,change.catalog_item_code,change.category,change.status,change.surcharge_amount::text,change.currency,change.requested_at::text,change.due_at::text,change.created_at::text,change.updated_at::text
 FROM client_changes change
 JOIN projects project ON project.tenant_id=change.tenant_id AND project.id=change.project_id
 JOIN units unit ON unit.tenant_id=change.tenant_id AND unit.id=change.unit_id
 JOIN parties party ON party.tenant_id=change.tenant_id AND party.id=change.party_id`;

export class ClientChangeRepository{constructor(private readonly database:Database){}
 async list(input:{tenantId:string;userId:string;membershipId:string;projectId?:string;unitId?:string}){return this.database.withContext({tenantId:input.tenantId,userId:input.userId},async client=>{const result=await client.query<ClientChangeRow>(`${select} WHERE change.tenant_id=$1 AND change.archived_at IS NULL AND ($2::uuid IS NULL OR change.project_id=$2) AND ($3::uuid IS NULL OR change.unit_id=$3) AND app.has_project_permission(change.tenant_id,$4,change.project_id,'client_changes.read') ORDER BY change.requested_at DESC,change.created_at DESC`,[input.tenantId,input.projectId??null,input.unitId??null,input.membershipId]);return result.rows.map(dto);});}
 async create(input:{tenantId:string;userId:string;membershipId:string;projectId:string;unitId:string;partyId:string;title:string;description?:string;sourceType:"individual"|"catalog";catalogItemCode?:string;category:string;surchargeAmount?:number|null;currency?:string;requestedAt:string;dueAt?:string|null}){return this.database.withContext({tenantId:input.tenantId,userId:input.userId},async client=>{const created=await client.query<{id:string}>("SELECT app.create_client_change($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) id",[input.tenantId,input.projectId,input.unitId,input.partyId,input.title,input.description??"",input.sourceType,input.catalogItemCode??"",input.category,input.surchargeAmount??null,input.currency??"CZK",input.requestedAt,input.dueAt??null,input.membershipId]);const result=await client.query<ClientChangeRow>(`${select} WHERE change.tenant_id=$1 AND change.id=$2`,[input.tenantId,created.rows[0].id]);return dto(result.rows[0]);});}
 async archive(input:{tenantId:string;userId:string;membershipId:string;changeId:string;reason:string}){return this.database.withContext({tenantId:input.tenantId,userId:input.userId},async client=>{await client.query("SELECT app.archive_client_change($1,$2,$3,$4)",[input.tenantId,input.changeId,input.membershipId,input.reason]);return{id:input.changeId,archived:true};});}
}
