import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {PGlite} from "@electric-sql/pglite";

const migrations=["0001_block_a_identity.sql","0002_block_b_inventory.sql","0003_block_c_sales.sql","0004_block_d_pricing_contracts.sql","0005_pilot_import_compatibility.sql","0006_crud_operations.sql"];
const tenant="d0000000-0000-4000-8000-000000000001";const actor="d3000000-0000-4000-8000-000000000002";const user="d1000000-0000-4000-8000-000000000002";
async function database(){const db=new PGlite();for(const name of migrations)await db.exec(await readFile(new URL(`../migrations/${name}`,import.meta.url),"utf8"));for(const name of ["0001_preview_block_b.sql","0002_preview_block_c.sql","0003_preview_block_d.sql"])await db.exec(await readFile(new URL(`../seeds/${name}`,import.meta.url),"utf8"));await db.exec(await readFile(new URL("../migrations/0007_practical_editing_rbac.sql",import.meta.url),"utf8"));await db.exec(`SELECT set_config('app.user_id','${user}',false);SELECT set_config('app.tenant_id','${tenant}',false);`);return db;}

test("praktická editace zavede citlivá granular permissions a append-only fázi projektu",async()=>{const db=await database();const codes=(await db.query<{code:string}>("SELECT code FROM permissions WHERE code IN ('projects.change_manager','projects.change_status','prices.change','prices.approve','holds.cancel') ORDER BY code")).rows.map(row=>row.code);assert.deepEqual(codes,["holds.cancel","prices.approve","prices.change","projects.change_manager","projects.change_status"]);const project=(await db.query<{id:string}>("SELECT id FROM projects WHERE tenant_id=$1 AND code='RJ'",[tenant])).rows[0];const before=(await db.query("SELECT id FROM construction_status_events WHERE tenant_id=$1 AND project_id=$2",[tenant,project.id])).rows.length;await db.query("SELECT app.record_project_construction_status($1,$2,'completed',now(),'Kontrolní dokončení',$3)",[tenant,project.id,actor]);assert.equal((await db.query("SELECT id FROM construction_status_events WHERE tenant_id=$1 AND project_id=$2",[tenant,project.id])).rows.length,before+1);await assert.rejects(db.query("UPDATE construction_status_events SET note='x' WHERE tenant_id=$1 AND project_id=$2",[tenant,project.id]),/append-only/i);await db.close();});

test("editace jednotky odmítne strukturu z jiného projektu a zachová audit",async()=>{const db=await database();const unit=(await db.query<{id:string}>("SELECT id FROM units WHERE tenant_id=$1 AND code='A203'",[tenant])).rows[0];const foreignStructure=(await db.query<{id:string}>("SELECT structure.id FROM project_structures structure JOIN projects project ON project.tenant_id=structure.tenant_id AND project.id=structure.project_id WHERE project.code='PČ' LIMIT 1")).rows[0];await assert.rejects(db.query("SELECT app.update_unit_details_v2($1,$2,$3,'3+kk','2. NP',2,82.4,82.4,'J',NULL,NULL,NULL,$4)",[tenant,unit.id,foreignStructure.id,actor]),/structure must belong/i);await db.query("SELECT app.update_unit_details_v2($1,$2,NULL,'3+kk','2. NP',2,83.1,82.4,'J',NULL,NULL,NULL,$3)",[tenant,unit.id,actor]);assert.equal((await db.query<{area:number}>("SELECT area_m2::float8 area FROM units WHERE tenant_id=$1 AND id=$2",[tenant,unit.id])).rows[0].area,83.1);assert.equal((await db.query("SELECT id FROM audit_log WHERE tenant_id=$1 AND entity_id=$2 AND action='unit.updated'",[tenant,unit.id])).rows.length,1);await db.close();});
