import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {PGlite} from "@electric-sql/pglite";

const tenant="d0000000-0000-4000-8000-000000000001",member="d3000000-0000-4000-8000-000000000001",unit="f0000000-0000-4000-8000-000000000001";
async function fixture(){const db=new PGlite();for(const name of ["0001_block_a_identity.sql","0002_block_b_inventory.sql","0003_block_c_sales.sql","0004_block_d_pricing_contracts.sql","0011_v31_workflow_and_administration.sql"])await db.exec(await readFile(new URL(`../migrations/${name}`,import.meta.url),"utf8"));for(const name of ["0001_preview_block_b.sql","0002_preview_block_c.sql","0003_preview_block_d.sql"])await db.exec(await readFile(new URL(`../seeds/${name}`,import.meta.url),"utf8"));await db.exec(await readFile(new URL("../migrations/0012_v32_granular_rbac_profiles_and_price_approval.sql",import.meta.url),"utf8"));return db;}

test("v32 oddělí provozní administraci od obchodního schvalování",async()=>{const db=await fixture();const roles=await db.query<{code:string;permissions:string[]}>("SELECT role.code,array_agg(permission.code ORDER BY permission.code) permissions FROM roles role JOIN role_permissions grant_row ON grant_row.tenant_id=role.tenant_id AND grant_row.role_id=role.id JOIN permissions permission ON permission.id=grant_row.permission_id WHERE role.tenant_id=$1 AND role.code IN ('admin','executive') GROUP BY role.code",[tenant]);const admin=roles.rows.find(row=>row.code==="admin")!,executive=roles.rows.find(row=>row.code==="executive")!;assert.ok(admin.permissions.includes("system.manage"));assert.ok(!admin.permissions.includes("prices.approve"));assert.ok(executive.permissions.includes("prices.approve"));assert.ok(!executive.permissions.includes("system.manage"));await db.close();});

test("návrh ceny nezmění aktuální cenu a až schválení vytvoří append-only záznam",async()=>{const db=await fixture();await db.exec(`INSERT INTO role_assignments(tenant_id,membership_id,role_id,assigned_by_user_id) SELECT '${tenant}','${member}',id,'d1000000-0000-4000-8000-000000000001' FROM roles WHERE tenant_id='${tenant}' AND code='admin' ON CONFLICT DO NOTHING;SET ROLE develocrm_app;SELECT set_config('app.tenant_id','${tenant}',false);SELECT set_config('app.user_id','d1000000-0000-4000-8000-000000000001',false);`);const before=(await db.query<{amount:number}>("SELECT app.current_unit_price($1,$2)::float8 amount",[tenant,unit])).rows[0].amount;const proposal=(await db.query<{id:string}>("SELECT app.propose_unit_price($1,$2,'contract_price',9100000,'CZK','2026-08-01','Aktualizace ceníku',$3) id",[tenant,unit,member])).rows[0].id;assert.equal((await db.query<{amount:number}>("SELECT app.current_unit_price($1,$2)::float8 amount",[tenant,unit])).rows[0].amount,before);await assert.rejects(db.query("SELECT app.decide_unit_price_proposal($1,$2,'approved','Schváleno',$3)",[tenant,proposal,member]),/prices.approve/);await db.exec("RESET ROLE");const executive=(await db.query<{id:string}>("SELECT id FROM roles WHERE tenant_id=$1 AND code='executive'",[tenant])).rows[0].id;await db.query("INSERT INTO role_assignments(tenant_id,membership_id,role_id,assigned_by_user_id) VALUES($1,$2,$3,'d1000000-0000-4000-8000-000000000001')",[tenant,member,executive]);await db.exec(`SET ROLE develocrm_app;SELECT set_config('app.tenant_id','${tenant}',false);SELECT set_config('app.user_id','d1000000-0000-4000-8000-000000000001',false);`);await db.query("SELECT app.decide_unit_price_proposal($1,$2,'approved','Schváleno jednatelem',$3)",[tenant,proposal,member]);assert.equal((await db.query<{amount:number}>("SELECT app.current_unit_price($1,$2,'2026-08-02')::float8 amount",[tenant,unit])).rows[0].amount,9100000);await db.close();});
