import assert from "node:assert/strict";
import {readFile,readdir} from "node:fs/promises";
import test from "node:test";
import {PGlite} from "@electric-sql/pglite";
import {bootstrapIds,bootstrapPilotWorkspace,normalizeBootstrapInput} from "../src/iam/pilot-bootstrap.js";
import {importDejvice} from "../src/imports/dejvice.js";
import {TaskRepository} from "../src/tasks/repository.js";
import type {Database} from "../src/database.js";

async function migrated(){const db=new PGlite();const directory=new URL("../migrations/",import.meta.url);for(const name of (await readdir(directory)).filter(name=>/^\d+.*\.sql$/.test(name)).sort())await db.exec(await readFile(new URL(name,directory),"utf8"));return db;}
function clientFor(db:PGlite){return{query:async(sql:string,parameters?:unknown[])=>{if(!parameters&&sql.includes(";")){await db.exec(sql);return{rows:[],rowCount:null};}const result=await db.query(sql,parameters as never[]|undefined);return{rows:result.rows,rowCount:result.affectedRows??null};}} as never;}

test("plánování předání je auditované a dovolí jen jedno otevřené předání jednotky",async()=>{
  const db=await migrated();const normalized=normalizeBootstrapInput({entraTenantId:"10000000-0000-4000-8000-000000000042",adminOid:"20000000-0000-4000-8000-000000000042",adminEmail:"mvp.admin@example.test",adminName:"MVP Admin",workspaceName:"MVP workspace",workspaceId:"30000000-0000-4000-8000-000000000042"});const ids=bootstrapIds(normalized);const client=clientFor(db);await bootstrapPilotWorkspace(client,{...normalized,...ids});const source=await readFile(new URL("../seeds/0004_pilot_rezidence_dejvice.sql",import.meta.url),"utf8");await importDejvice(client,source,{tenantId:ids.tenantId,membershipId:ids.membershipId,dryRun:false});
  await db.exec(`SELECT set_config('app.tenant_id','${ids.tenantId}',false);SELECT set_config('app.user_id','${ids.userId}',false);`);
  const unit=(await db.query<{id:string}>("SELECT id FROM units WHERE tenant_id=$1 AND code='101'",[ids.tenantId])).rows[0];
  const handover=(await db.query<{id:string}>("SELECT app.schedule_unit_handover($1,$2,now()+interval '7 days',$3,$3) id",[ids.tenantId,unit.id,ids.membershipId])).rows[0].id;
  assert.equal((await db.query("SELECT id FROM audit_log WHERE tenant_id=$1 AND entity_id=$2 AND action='handover.scheduled'",[ids.tenantId,handover])).rows.length,1);
  assert.equal((await db.query("SELECT id FROM outbox_events WHERE tenant_id=$1 AND aggregate_id=$2 AND event_type='handover.scheduled.v1'",[ids.tenantId,handover])).rows.length,1);
  await assert.rejects(db.query("SELECT app.schedule_unit_handover($1,$2,now()+interval '8 days',$3,$3)",[ids.tenantId,unit.id,ids.membershipId]),/active handover|unique/i);
  await db.close();
});

test("handover repository používá skutečný název role účastníka a kanonické oprávnění",async()=>{const source=await readFile(new URL("../src/handovers/repository.ts",import.meta.url),"utf8");assert.match(source,/participant\.participant_role/);assert.doesNotMatch(source,/participant\.role\b/);assert.match(source,/handovers\.read/);});
test("klientský endpoint stránkuje a zachovává kombinované filtry na backendu",async()=>{const repository=await readFile(new URL("../src/sales/repository.ts",import.meta.url),"utf8");const app=await readFile(new URL("../src/app.ts",import.meta.url),"utf8");assert.match(repository,/async getPage/);assert.match(repository,/total,page,pageSize/);assert.match(app,/request\.query\.page/);assert.match(app,/types:request\.query\.types/);});

test("projektová média, vedoucí, fáze a úkol používají produkční UUID a auditované doménové operace",async()=>{
  const db=await migrated();const normalized=normalizeBootstrapInput({entraTenantId:"10000000-0000-4000-8000-000000000043",adminOid:"20000000-0000-4000-8000-000000000043",adminEmail:"project.admin@example.test",adminName:"Project Admin",workspaceName:"Project workspace",workspaceId:"30000000-0000-4000-8000-000000000043"});const ids=bootstrapIds(normalized);const client=clientFor(db);await bootstrapPilotWorkspace(client,{...normalized,...ids});const source=await readFile(new URL("../seeds/0004_pilot_rezidence_dejvice.sql",import.meta.url),"utf8");await importDejvice(client,source,{tenantId:ids.tenantId,membershipId:ids.membershipId,dryRun:false});
  await db.exec(`SELECT set_config('app.tenant_id','${ids.tenantId}',false);SELECT set_config('app.user_id','${ids.userId}',false);`);
  const project=(await db.query<{id:string;name:string}>("SELECT id,name FROM projects WHERE tenant_id=$1 AND code='DEJ'",[ids.tenantId])).rows[0];const unit=(await db.query<{id:string}>("SELECT id FROM units WHERE tenant_id=$1 AND project_id=$2 ORDER BY code LIMIT 1",[ids.tenantId,project.id])).rows[0];
  assert.equal((await db.query<{allowed:boolean}>("SELECT app.has_project_permission($1,$2,$3,'media.manage') allowed",[ids.tenantId,ids.membershipId,project.id])).rows[0].allowed,true);
  await db.query("SELECT app.set_project_cover($1,$2,'/api/media/file/test','image/png','crm','test-key',$3)",[ids.tenantId,project.id,ids.membershipId]);assert.equal((await db.query("SELECT id FROM audit_log WHERE tenant_id=$1 AND entity_id=$2 AND action='project.cover_changed'",[ids.tenantId,project.id])).rows.length,1);
  const newUser="40000000-0000-4000-8000-000000000043",newMembership="50000000-0000-4000-8000-000000000043";await db.query("INSERT INTO users(id,entra_issuer,entra_subject,email,display_name) VALUES($1,'issuer','manager-oid','manager@example.test','Nový vedoucí')",[newUser]);await db.query("INSERT INTO tenant_memberships(id,tenant_id,user_id,status,accepted_at) VALUES($1,$2,$3,'active',now())",[newMembership,ids.tenantId,newUser]);
  await db.query("SELECT app.update_project_details($1,$2,$3,'Praha','active',$4,NULL,NULL,$5)",[ids.tenantId,project.id,project.name,newMembership,ids.membershipId]);assert.equal((await db.query<{count:number}>("SELECT count(*)::int count FROM project_role_assignments assignment JOIN roles role ON role.tenant_id=assignment.tenant_id AND role.id=assignment.role_id WHERE assignment.tenant_id=$1 AND assignment.project_id=$2 AND assignment.membership_id=$3 AND role.code='project_manager'",[ids.tenantId,project.id,newMembership])).rows[0].count,1);
  await db.query("SELECT app.record_project_construction_status($1,$2,'fit_out',now(),'Aktualizace pilotní fáze',$3)",[ids.tenantId,project.id,ids.membershipId]);assert.equal((await db.query("SELECT id FROM construction_status_events WHERE tenant_id=$1 AND project_id=$2 AND status_code='fit_out'",[ids.tenantId,project.id])).rows.length,1);
  const adapter={withContext:async<T>(context:{tenantId:string;userId:string},work:(queryClient:{query:(sql:string,parameters?:unknown[])=>Promise<{rows:unknown[];rowCount:number|null}>})=>Promise<T>)=>{await db.exec(`SELECT set_config('app.tenant_id','${context.tenantId}',false);SELECT set_config('app.user_id','${context.userId}',false);`);return work({query:async(sql,parameters)=>{const result=await db.query(sql,parameters as never[]|undefined);return{rows:result.rows,rowCount:result.affectedRows??result.rows.length};}});}} as unknown as Database;const tasks=new TaskRepository(adapter);const created=await tasks.create({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,projectId:project.id,unitId:unit.id,title:"Kontrolní úkol",description:"Regresní test",priority:"high",dueAt:new Date().toISOString(),assigneeMembershipId:ids.membershipId});assert.equal(created.objectType,"unit");assert.match(created.objectLabel,/Jednotka/);assert.equal(created.projectId,project.id);await tasks.archive({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,taskId:created.id});assert.equal((await db.query<{status:string}>("SELECT status FROM tasks WHERE tenant_id=$1 AND id=$2",[ids.tenantId,created.id])).rows[0].status,"cancelled");await db.close();
});

test("prodejní výkon Rezidence Dejvice zahrnuje rezervované jednotky",async()=>{
  const db=await migrated();const normalized=normalizeBootstrapInput({entraTenantId:"10000000-0000-4000-8000-000000000044",adminOid:"20000000-0000-4000-8000-000000000044",adminEmail:"sales.admin@example.test",adminName:"Sales Admin",workspaceName:"Sales workspace",workspaceId:"30000000-0000-4000-8000-000000000044"});const ids=bootstrapIds(normalized);const client=clientFor(db);await bootstrapPilotWorkspace(client,{...normalized,...ids});const source=await readFile(new URL("../seeds/0004_pilot_rezidence_dejvice.sql",import.meta.url),"utf8");await importDejvice(client,source,{tenantId:ids.tenantId,membershipId:ids.membershipId,dryRun:false});const counts=(await db.query<{status:string;count:number}>("SELECT commercial_status status,count(*)::int count FROM units WHERE tenant_id=$1 GROUP BY commercial_status",[ids.tenantId])).rows;const byStatus=Object.fromEntries(counts.map(row=>[row.status,row.count]));assert.equal(byStatus.reserved,2);assert.equal(byStatus.sold??0,0);assert.equal(byStatus.handed_over??0,0);assert.equal((byStatus.reserved??0)+(byStatus.contracted??0)+(byStatus.sold??0)+(byStatus.handed_over??0),2);await db.close();
});

test("klientská změna je provázaná, auditovaná a bezpečně archivovatelná",async()=>{
  const db=await migrated();const normalized=normalizeBootstrapInput({entraTenantId:"10000000-0000-4000-8000-000000000045",adminOid:"20000000-0000-4000-8000-000000000045",adminEmail:"changes.admin@example.test",adminName:"Changes Admin",workspaceName:"Changes workspace",workspaceId:"30000000-0000-4000-8000-000000000045"});const ids=bootstrapIds(normalized);const client=clientFor(db);await bootstrapPilotWorkspace(client,{...normalized,...ids});const source=await readFile(new URL("../seeds/0004_pilot_rezidence_dejvice.sql",import.meta.url),"utf8");await importDejvice(client,source,{tenantId:ids.tenantId,membershipId:ids.membershipId,dryRun:false});await db.exec(`SELECT set_config('app.tenant_id','${ids.tenantId}',false);SELECT set_config('app.user_id','${ids.userId}',false);`);
  const context=(await db.query<{project_id:string;unit_id:string;party_id:string}>("SELECT unit.project_id,unit.id unit_id,link.party_id FROM units unit JOIN party_project_links link ON link.tenant_id=unit.tenant_id AND link.project_id=unit.project_id AND link.valid_to IS NULL WHERE unit.tenant_id=$1 ORDER BY unit.code LIMIT 1",[ids.tenantId])).rows[0];
  const created=(await db.query<{id:string}>("SELECT app.create_client_change($1,$2,$3,$4,'Kontrolní klientská změna','Regresní test','individual','', 'Povrchy',12500,'CZK',current_date,current_date+30,$5) id",[ids.tenantId,context.project_id,context.unit_id,context.party_id,ids.membershipId])).rows[0].id;
  assert.equal((await db.query("SELECT id FROM client_changes WHERE tenant_id=$1 AND id=$2 AND unit_id=$3 AND party_id=$4",[ids.tenantId,created,context.unit_id,context.party_id])).rows.length,1);
  assert.equal((await db.query("SELECT id FROM audit_log WHERE tenant_id=$1 AND entity_id=$2 AND action='client_change.created'",[ids.tenantId,created])).rows.length,1);
  assert.equal((await db.query("SELECT id FROM outbox_events WHERE tenant_id=$1 AND aggregate_id=$2 AND event_type='client_change.created.v1'",[ids.tenantId,created])).rows.length,1);
  await db.query("SELECT app.archive_client_change($1,$2,$3,'Ukončení regresního testu')",[ids.tenantId,created,ids.membershipId]);
  assert.equal((await db.query<{status:string}>("SELECT status FROM client_changes WHERE tenant_id=$1 AND id=$2",[ids.tenantId,created])).rows[0].status,"archived");
  await db.close();
});
