import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {PGlite} from "@electric-sql/pglite";

const tenant="d0000000-0000-4000-8000-000000000001";
const user="d1000000-0000-4000-8000-000000000001";
const member="d3000000-0000-4000-8000-000000000001";
const salesCase="c6000000-0000-4000-8000-000000000002";

async function source(path:string){return readFile(new URL(path,import.meta.url),"utf8");}
async function base(){const db=new PGlite();for(const name of ["0001_block_a_identity.sql","0002_block_b_inventory.sql","0003_block_c_sales.sql","0004_block_d_pricing_contracts.sql","0011_v31_workflow_and_administration.sql"])await db.exec(await source(`../migrations/${name}`));for(const name of ["0001_preview_block_b.sql","0002_preview_block_c.sql","0003_preview_block_d.sql"])await db.exec(await source(`../seeds/${name}`));await db.exec(await source("../migrations/0014_payments_and_reservation_activation.sql"));await db.exec(`INSERT INTO role_assignments(tenant_id,membership_id,role_id,assigned_by_user_id) VALUES('${tenant}','${member}','d4000000-0000-4000-8000-000000000001','${user}') ON CONFLICT DO NOTHING`);return db;}
async function asApp(db:PGlite){await db.exec(`SET ROLE develocrm_app;SELECT set_config('app.user_id','${user}',false);SELECT set_config('app.tenant_id','${tenant}',false);`);}

test("migrace doplní chybějící logickou verzi a umožní schválení RS",async()=>{const db=await base();await asApp(db);const contract=(await db.query<{id:string}>("SELECT app.create_contract($1,$2,'rs','LEGACY-RS-001','Starší RS',$3,NULL) id",[tenant,salesCase,member])).rows[0].id;for(const state of ["sent","negotiation"])await db.query("SELECT app.transition_contract_status($1,$2,$3,'Test workflow',$4)",[tenant,contract,state,member]);await db.exec("RESET ROLE");assert.equal((await db.query("SELECT id FROM contract_versions WHERE contract_id=$1",[contract])).rows.length,0);await db.exec(await source("../migrations/0020_core_sales_workflow.sql"));await asApp(db);await db.query("SELECT app.transition_contract_status($1,$2,'approved','',$3)",[tenant,contract,member]);assert.equal((await db.query<{current_status:string}>("SELECT current_status FROM contracts WHERE id=$1",[contract])).rows[0].current_status,"approved");assert.equal((await db.query("SELECT id FROM contract_versions WHERE contract_id=$1 AND version_status='approved_for_signing'",[contract])).rows.length,1);await db.close();});

test("vytvoření RS atomicky založí verzi, účastníky a jedinou platební povinnost",async()=>{const db=await base();await db.exec(await source("../migrations/0020_core_sales_workflow.sql"));await asApp(db);const key="contract-create-test-1";const params=[tenant,salesCase,"rs","RS-PAYMENT-001","Rezervační smlouva",member,null,key,"percentage",2,new Date(Date.now()+5*86400000).toISOString()];const first=(await db.query<{contract_id:string;version_id:string;payment_obligation_id:string;payment_amount:number}>("SELECT * FROM app.create_contract_with_payment($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",params)).rows[0];const second=(await db.query<{contract_id:string;payment_obligation_id:string}>("SELECT * FROM app.create_contract_with_payment($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",params)).rows[0];assert.equal(second.contract_id,first.contract_id);assert.equal(second.payment_obligation_id,first.payment_obligation_id);assert.equal(Number(first.payment_amount),249800);assert.equal((await db.query("SELECT id FROM contract_versions WHERE contract_id=$1",[first.contract_id])).rows.length,1);assert.ok((await db.query("SELECT id FROM contract_parties WHERE contract_id=$1",[first.contract_id])).rows.length>=1);assert.equal((await db.query("SELECT id FROM payment_obligations WHERE contract_id=$1",[first.contract_id])).rows.length,1);assert.ok((await db.query("SELECT id FROM audit_log WHERE entity_id IN ($1,$2)",[first.contract_id,first.payment_obligation_id])).rows.length>=2);assert.ok((await db.query("SELECT id FROM outbox_events WHERE aggregate_id IN ($1,$2)",[first.contract_id,first.payment_obligation_id])).rows.length>=2);await db.close();});

test("SBK ukládá pevnou částku a retry nevytvoří druhý předpis",async()=>{const db=await base();await db.exec(await source("../migrations/0020_core_sales_workflow.sql"));await asApp(db);const due=new Date(Date.now()+7*86400000).toISOString();const result=(await db.query<{contract_id:string;payment_amount:number}>("SELECT * FROM app.create_contract_with_payment($1,$2,'sbk','SBK-PAYMENT-001','Budoucí kupní smlouva',$3,NULL,'contract-create-test-2','fixed',250000,$4)",[tenant,salesCase,member,due])).rows[0];assert.equal(Number(result.payment_amount),250000);assert.equal((await db.query("SELECT id FROM payment_obligations WHERE contract_id=$1 AND obligation_type='purchase_installment'",[result.contract_id])).rows.length,1);await db.query("SELECT * FROM app.create_contract_with_payment($1,$2,'sbk','SBK-PAYMENT-001','Budoucí kupní smlouva',$3,NULL,'contract-create-test-2','fixed',250000,$4)",[tenant,salesCase,member,due]);assert.equal((await db.query("SELECT id FROM payment_obligations WHERE contract_id=$1",[result.contract_id])).rows.length,1);await db.close();});
