import assert from "node:assert/strict";
import { readdir,readFile } from "node:fs/promises";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { bootstrapIds,bootstrapPilotWorkspace,normalizeBootstrapInput } from "../src/iam/pilot-bootstrap.js";
import { importDejvice } from "../src/imports/dejvice.js";

async function migrated(){const db=new PGlite();const directory=new URL("../migrations/",import.meta.url);for(const name of (await readdir(directory)).filter(name=>/^\d+.*\.sql$/.test(name)).sort())await db.exec(await readFile(new URL(name,directory),"utf8"));return db;}
function clientFor(db:PGlite){return{query:async(sql:string,parameters?:unknown[])=>{if(!parameters&&sql.includes(";")){await db.exec(sql);return{rows:[],rowCount:null};}const result=await db.query(sql,parameters as never[]|undefined);return{rows:result.rows,rowCount:result.affectedRows??null};}} as never;}
async function pilot(){const db=await migrated();const normalized=normalizeBootstrapInput({entraTenantId:"10000000-0000-4000-8000-000000000046",adminOid:"20000000-0000-4000-8000-000000000046",adminEmail:"sales-flow@example.test",adminName:"Sales Flow Admin",workspaceName:"Sales Flow",workspaceId:"30000000-0000-4000-8000-000000000046"});const ids=bootstrapIds(normalized);const client=clientFor(db);await bootstrapPilotWorkspace(client,{...normalized,...ids});const source=await readFile(new URL("../seeds/0004_pilot_rezidence_dejvice.sql",import.meta.url),"utf8");await importDejvice(client,source,{tenantId:ids.tenantId,membershipId:ids.membershipId,dryRun:false});await db.exec(`SELECT set_config('app.tenant_id','${ids.tenantId}',false);SELECT set_config('app.user_id','${ids.userId}',false);`);return{db,ids};}

test("nový klient a předrezervace vzniknou atomicky s clients.create bez předchozího party scope",async()=>{const{db,ids}=await pilot();const unit=(await db.query<{id:string}>("SELECT id FROM units WHERE tenant_id=$1 AND commercial_status='available' ORDER BY code LIMIT 1",[ids.tenantId])).rows[0];const key="new-party-pre-reservation";
  const created=(await db.query<{party_id:string;sales_case_id:string;hold_id:string}>("SELECT * FROM app.create_party_and_unit_hold($1,$2,'pre_reservation',now()+interval '48 hours',$3,$4,'Vytvořena předrezervace','individual','paní','Jana','Nováková',NULL,NULL,'jana.novakova@example.test','+420700000046')",[ids.tenantId,unit.id,ids.membershipId,key])).rows[0];
  assert.ok(created.party_id);assert.ok(created.sales_case_id);assert.ok(created.hold_id);
  assert.equal((await db.query<{salutation:string}>("SELECT salutation FROM party_individual_details WHERE tenant_id=$1 AND party_id=$2",[ids.tenantId,created.party_id])).rows[0].salutation,"paní");
  assert.equal((await db.query<{commercial_status:string}>("SELECT commercial_status FROM units WHERE tenant_id=$1 AND id=$2",[ids.tenantId,unit.id])).rows[0].commercial_status,"pre_reserved");
  assert.ok((await db.query("SELECT id FROM party_project_links WHERE tenant_id=$1 AND party_id=$2 AND valid_to IS NULL",[ids.tenantId,created.party_id])).rows.length>=1);
  assert.equal((await db.query("SELECT id FROM unit_interests WHERE tenant_id=$1 AND unit_id=$2 AND party_id=$3",[ids.tenantId,unit.id,created.party_id])).rows.length,1);
  assert.ok((await db.query("SELECT id FROM audit_log WHERE tenant_id=$1 AND entity_id=ANY($2::uuid[])",[ids.tenantId,[created.party_id,created.hold_id]])).rows.length>=2);
  const retry=(await db.query<{party_id:string;hold_id:string}>("SELECT * FROM app.create_party_and_unit_hold($1,$2,'pre_reservation',now()+interval '48 hours',$3,$4,'Vytvořena předrezervace','individual','paní','Jana','Nováková',NULL,NULL,'jana.novakova@example.test','+420700000046')",[ids.tenantId,unit.id,ids.membershipId,key])).rows[0];assert.equal(retry.party_id,created.party_id);assert.equal(retry.hold_id,created.hold_id);assert.equal((await db.query("SELECT id FROM parties WHERE tenant_id=$1 AND display_name='Jana Nováková'",[ids.tenantId])).rows.length,1);await db.close();
});

test("existující klient může vytvořit předrezervaci stávající doménovou operací",async()=>{const{db,ids}=await pilot();const unit=(await db.query<{id:string}>("SELECT id FROM units WHERE tenant_id=$1 AND commercial_status='available' ORDER BY code LIMIT 1",[ids.tenantId])).rows[0];const party=(await db.query<{id:string}>("SELECT party.id FROM parties party JOIN party_project_links link ON link.tenant_id=party.tenant_id AND link.party_id=party.id WHERE party.tenant_id=$1 ORDER BY party.created_at LIMIT 1",[ids.tenantId])).rows[0];const result=await db.query("SELECT * FROM app.create_unit_hold($1,$2,'pre_reservation',ARRAY[$3]::uuid[],now()+interval '24 hours',$4,NULL,'existing-party-pre-reservation','Vytvořena předrezervace')",[ids.tenantId,unit.id,party.id,ids.membershipId]);assert.equal(result.rows.length,1);await db.close();});

test("uživatel bez clients.create dostane 403 ekvivalent a Admin získá všechny potřebné permission",async()=>{const{db,ids}=await pilot();const project=(await db.query<{id:string}>("SELECT id FROM projects WHERE tenant_id=$1 LIMIT 1",[ids.tenantId])).rows[0];const unit=(await db.query<{id:string}>("SELECT id FROM units WHERE tenant_id=$1 AND project_id=$2 AND commercial_status='available' ORDER BY code LIMIT 1",[ids.tenantId,project.id])).rows[0];const user="40000000-0000-4000-8000-000000000046",membership="50000000-0000-4000-8000-000000000046";const role=(await db.query<{id:string}>("SELECT id FROM roles WHERE tenant_id=$1 AND code='sales'",[ids.tenantId])).rows[0].id;await db.query("DELETE FROM role_permissions WHERE tenant_id=$1 AND role_id=$2 AND permission_id=(SELECT id FROM permissions WHERE code='clients.create')",[ids.tenantId,role]);await db.query("INSERT INTO users(id,entra_issuer,entra_subject,email,display_name) VALUES($1,'issuer','restricted','restricted@example.test','Restricted')",[user]);await db.query("INSERT INTO tenant_memberships(id,tenant_id,user_id,status,accepted_at) VALUES($1,$2,$3,'active',now())",[membership,ids.tenantId,user]);await db.query("INSERT INTO project_role_assignments(tenant_id,project_id,membership_id,role_id,assigned_by_user_id) VALUES($1,$2,$3,$4,$5)",[ids.tenantId,project.id,membership,role,ids.userId]);await db.exec(`SELECT set_config('app.user_id','${user}',false);`);await assert.rejects(db.query("SELECT * FROM app.create_party_and_unit_hold($1,$2,'pre_reservation',now()+interval '24 hours',$3,'denied-new-party','Vytvořena předrezervace','individual',NULL,'Bez','Oprávnění',NULL,NULL,NULL,NULL)",[ids.tenantId,unit.id,membership]),/clients\.create permission required/i);const adminPermissions=(await db.query<{code:string}>("SELECT permission.code FROM roles role JOIN role_permissions grant_row ON grant_row.tenant_id=role.tenant_id AND grant_row.role_id=role.id JOIN permissions permission ON permission.id=grant_row.permission_id WHERE role.tenant_id=$1 AND role.code='admin' AND permission.code=ANY($2::text[])",[ids.tenantId,['clients.create','clients.update','interests.manage','sales_cases.manage','holds.create']])).rows.map(row=>row.code);assert.equal(new Set(adminPermissions).size,5);await db.close();});
