import assert from "node:assert/strict";
import {readdir,readFile} from "node:fs/promises";
import test from "node:test";
import {PGlite} from "@electric-sql/pglite";
import type {Database} from "../src/database.js";
import {bootstrapIds,bootstrapPilotWorkspace,normalizeBootstrapInput} from "../src/iam/pilot-bootstrap.js";
import {importDejvice} from "../src/imports/dejvice.js";
import {SalesRepository} from "../src/sales/repository.js";

async function setup(){const db=new PGlite();const directory=new URL("../migrations/",import.meta.url);for(const name of (await readdir(directory)).filter(name=>/^\d+.*\.sql$/.test(name)).sort())await db.exec(await readFile(new URL(name,directory),"utf8"));const normalized=normalizeBootstrapInput({entraTenantId:"10000000-0000-4000-8000-000000000047",adminOid:"20000000-0000-4000-8000-000000000047",adminEmail:"client-integrity@example.test",adminName:"Client Integrity Admin",workspaceName:"Client Integrity",workspaceId:"30000000-0000-4000-8000-000000000047"});const ids=bootstrapIds(normalized);const client={query:async(sql:string,parameters?:unknown[])=>{if(!parameters&&sql.includes(";")){await db.exec(sql);return{rows:[],rowCount:null};}const result=await db.query(sql,parameters as never[]|undefined);return{rows:result.rows,rowCount:result.affectedRows??null};}} as never;await bootstrapPilotWorkspace(client,{...normalized,...ids});await importDejvice(client,await readFile(new URL("../seeds/0004_pilot_rezidence_dejvice.sql",import.meta.url),"utf8"),{tenantId:ids.tenantId,membershipId:ids.membershipId,dryRun:false});await db.exec(`SELECT set_config('app.tenant_id','${ids.tenantId}',false);SELECT set_config('app.user_id','${ids.userId}',false);`);const adapter={withContext:async<T>(context:{tenantId?:string;userId?:string},work:(sqlClient:{query:typeof db.query})=>Promise<T>)=>{await db.exec(`SELECT set_config('app.tenant_id','${context.tenantId??""}',false);SELECT set_config('app.user_id','${context.userId??""}',false);`);return work({query:async(text:string,values?:unknown[])=>{const result=await db.query(text,values as never[]|undefined);return{rows:result.rows,rowCount:result.affectedRows??null};}});}} as unknown as Database;return{db,ids,repository:new SalesRepository(adapter)};}

test("duplicate check rozlišuje normalizovaný e-mail, telefon, jméno a nový záznam",async()=>{const{db,ids,repository}=await setup();const project=(await db.query<{id:string}>("SELECT id FROM projects WHERE tenant_id=$1 AND code='DEJ'",[ids.tenantId])).rows[0];const created=await repository.createParty({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,projectId:project.id,kind:"individual",firstName:"Jana",lastName:"Duplicitní",email:"jana.duplicate@example.test",phone:"+420 777 888 947"});assert.ok(created?.id);
  const byEmail=await repository.findDuplicates({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,projectId:project.id,kind:"individual",firstName:"Jiná",lastName:"Osoba",email:"  JANA.DUPLICATE@EXAMPLE.TEST "});assert.equal(byEmail[0]?.strength,"strong");assert.ok(byEmail[0]?.reasons.includes("Stejný e-mail"));
  const byPhone=await repository.findDuplicates({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,projectId:project.id,kind:"individual",firstName:"Jiná",lastName:"Osoba",phone:"777888947"});assert.equal(byPhone[0]?.strength,"strong");assert.ok(byPhone[0]?.reasons.includes("Stejný telefon"));
  const byName=await repository.findDuplicates({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,projectId:project.id,kind:"individual",firstName:" JANA ",lastName:" DUPLICITNÍ "});assert.equal(byName[0]?.strength,"possible");assert.deepEqual(byName[0]?.reasons,["Stejné jméno nebo název"]);
  const fresh=await repository.findDuplicates({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,projectId:project.id,kind:"individual",firstName:"Úplně",lastName:"Nový",email:"nobody-47@example.test",phone:"+420 799 999 947"});assert.equal(fresh.length,0);
  await repository.linkPartyToProject({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,partyId:created.id,projectId:project.id});assert.equal((await db.query("SELECT count(*)::int count FROM parties WHERE tenant_id=$1 AND id=$2",[ids.tenantId,created.id])).rows[0].count,1);
  await repository.createParty({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,projectId:project.id,kind:"individual",firstName:"Jana",lastName:"Duplicitní druhá",email:"jana.duplicate@example.test",duplicateOverride:true});assert.equal((await db.query("SELECT count(*)::int count FROM parties WHERE tenant_id=$1 AND display_name LIKE 'Jana Duplicitní%'",[ids.tenantId])).rows[0].count,2);await db.close();});

test("klient bez historie se smaže, klient s historií se archivuje a audit zůstane",async()=>{const{db,ids,repository}=await setup();const project=(await db.query<{id:string}>("SELECT id FROM projects WHERE tenant_id=$1 AND code='DEJ'",[ids.tenantId])).rows[0];const created=await repository.createParty({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,projectId:project.id,kind:"individual",firstName:"Test",lastName:"Bez historie",email:"delete-47@example.test"});const cleanId=created?.id;assert.ok(cleanId);const cleanImpact=await repository.archiveImpact({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,partyId:cleanId});assert.equal(cleanImpact.removalMode,"delete");const deleted=await repository.archiveParty({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,partyId:cleanId,reason:"Test smazání"});assert.equal(deleted.mode,"delete");assert.equal((await db.query("SELECT id FROM parties WHERE tenant_id=$1 AND id=$2",[ids.tenantId,cleanId])).rows.length,0);assert.equal((await db.query("SELECT id FROM audit_log WHERE tenant_id=$1 AND entity_id=$2 AND action='party.deleted'",[ids.tenantId,cleanId])).rows.length,1);const historic=(await db.query<{id:string}>("SELECT party_id id FROM unit_interests WHERE tenant_id=$1 LIMIT 1",[ids.tenantId])).rows[0];const historicImpact=await repository.archiveImpact({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,partyId:historic.id});assert.equal(historicImpact.removalMode,"archive");const archived=await repository.archiveParty({tenantId:ids.tenantId,userId:ids.userId,membershipId:ids.membershipId,partyId:historic.id,reason:"Test archivace"});assert.equal(archived.mode,"archive");assert.equal((await db.query<{lifecycle_status:string}>("SELECT lifecycle_status FROM parties WHERE tenant_id=$1 AND id=$2",[ids.tenantId,historic.id])).rows[0].lifecycle_status,"archived");await db.close();});
