import type {ContractRecord,PriceHistoryRecord} from "../crm-data";
import {recordPreviewActivity} from "./activity-repository";
export type CommercialSnapshot={currentPrices:Record<string,number>;priceHistories:Record<string,PriceHistoryRecord[]>;contracts:ContractRecord[];contractSummary:Record<string,number>;source:"backend-api"|"preview-seed"};
export interface CommercialRepository{getSnapshot(signal?:AbortSignal):Promise<CommercialSnapshot>;recordPrice(input:{unitId:string;unitKey?:string;priceType:string;amount:number;validFrom:string;reason:string;approverMembershipId?:string}):Promise<void>;transitionContract(input:{contractId:string;to:string;reason:string}):Promise<void>}
class ApiCommercialRepository implements CommercialRepository{async getSnapshot(signal?:AbortSignal){const response=await fetch("/api/commercial",{signal,cache:"no-store"});if(!response.ok)throw new Error("Ceny a smlouvy se nepodařilo načíst");const snapshot=await response.json() as CommercialSnapshot;if(typeof window!=="undefined"){const edits=JSON.parse(localStorage.getItem("develocrm.price.edits")||"{}");for(const [unit,rows] of Object.entries(edits)){snapshot.priceHistories[unit]=[...(rows as PriceHistoryRecord[]),...(snapshot.priceHistories[unit]||[])];const first=(snapshot.priceHistories[unit]||[])[0];if(first)snapshot.currentPrices[unit]=first.amount;}const contractEdits=JSON.parse(localStorage.getItem("develocrm.contract.edits")||"{}");snapshot.contracts=snapshot.contracts.map(item=>({...item,...(item.id?contractEdits[item.id]:{})}));}return snapshot;}}
ApiCommercialRepository.prototype.recordPrice=async function(input){const {unitKey,...payload}=input;const r=await fetch("/api/commercial/prices",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(r.ok)return;if(r.status===503&&typeof window!=="undefined"){const key=unitKey??input.unitId;const rows=JSON.parse(localStorage.getItem("develocrm.price.edits")||"{}");rows[key]??=[];rows[key].unshift({id:`local-${Date.now()}`,unit:key,type:input.priceType,amount:input.amount,currency:"CZK",validFrom:input.validFrom,validTo:null,reason:input.reason,author:"Iva Novotná",approver:null});localStorage.setItem("develocrm.price.edits",JSON.stringify(rows));recordPreviewActivity({unitKey:key,title:"Zaznamenána nová cena jednotky",detail:`Iva Novotná · ${input.reason}`,icon:"price",action:"unit.price_recorded"});return;}const responsePayload=await r.json().catch(()=>({})) as {error?:string};throw new Error(responsePayload.error||"Cenu se nepodařilo uložit");};
ApiCommercialRepository.prototype.transitionContract=async function(input){const response=await fetch(`/api/commercial/contracts/${input.contractId}/status`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});if(response.ok)return;if(response.status===503&&typeof window!=="undefined"){const rows=JSON.parse(localStorage.getItem("develocrm.contract.edits")||"{}");rows[input.contractId]={statusCode:input.to,state:contractStatusLabel(input.to)};localStorage.setItem("develocrm.contract.edits",JSON.stringify(rows));return;}const payload=await response.json().catch(()=>({})) as {error?:string};throw new Error(payload.error||"Stav smlouvy se nepodařilo změnit");};
function contractStatusLabel(code:string){return ({draft:"V přípravě",sent:"Odeslána",negotiation:"Ve vyjednávání",approved:"Schválena",signing:"K podpisu",signed:"Podepsána",cancelled:"Zrušena",terminated:"Ukončena"} as Record<string,string>)[code]??code;}
export const commercialRepository:CommercialRepository=new ApiCommercialRepository();
